default:
  image: node:22
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - .npm/
 
  before_script:
    - npm ci --cache .npm --prefer--offline

stages:
  - test
  - publish
  - deploy

test:
  stage: test
  script:
    - npm test

publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - master
  script:
    - chmod og= $SERVER_KEY
    - apk update && apk add openssh-client
    - ssh -i $SERVER_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
    - ssh -i $SERVER_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - ssh -i $SERVER_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f klippify || true"
    - ssh -i $SERVER_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p $APP_PORT:$APP_PORT --name klippify $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"


